#DESPUES SE CREA EL COMPOSE EN LA CARPETA RAMA
#docker-compose up

version: '3'
services:
  # db:
  #   image: postgres
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: admin123
  #     POSTGRES_DB: gestionAlbergue
  #   ports:
  #     8080
  #   volumes:
  #     db:/var/lib/postgres

  app-frontend:
    image: gestion-front-image
    ports:
      - "88:88"
    restart: always
  
  # app-backend:
  #   depends_on:
  #     db
  #   image: gestion-back-image
  #   # ports:
  #   #   - "8008:8008"
  #   environment:
  #     - DB_HOST=db
  #     - DB_USER=postgres
  #     - DB_PASSWORD=admin123
  #     - DB_NAME=gestionAlbergue
  #     - DB_PORT=8008
  #   stdin_open: true
  #   tty: true

# volumes:
#   my-vol:

#AUNQUE YA CARGA EL FRONT Y SE HACE LA IMAGEN DEL BACK, COMO SERVER.JS TIENE REFERENCIA A UN ARCHIVO DE CLIENT EL SERVER CRASHEA
#ESTO SE DEBE A QUE, POR EL USO DE DOCKER CADA CARPETA SE PASA A UN ESPACIO TOTALMENTE DIFERENTE, POR LO QUE LA REFERENCIA NO
#ENCUENTRA NADA. SEGUN ESTO SE RESUELVE CON VOLUMES, PERO NO LO LOGRÉ, TAL VEZ JOSAFAT SEPA